In [70]:
import pandas as pd
import pickle
import datetime as dt
import os

## Priority Banding

In [71]:
filepath = "input_files/banding/pb_2020-08_100-30-10.pkl"
d1 = pickle.load(open(filepath, "rb"))
d1

{'start': datetime.datetime(2020, 8, 1, 0, 0),
 'end': datetime.datetime(2021, 2, 1, 0, 0),
 'horizon': 604800,
 'telescopes': {'2m0a.clma.coj': '2m0a.clma.coj',
  '2m0a.clma.ogg': '2m0a.clma.ogg'},
 'all_requests':                                           original_windows  \
 2333096  [{'start': 2020-12-22 06:52:00, 'end': 2020-12...
 2226632  [{'start': 2020-09-03 00:21:00, 'end': 2020-09...
 2287707  [{'start': 2020-11-07 12:50:00, 'end': 2020-11...
 2226876  [{'start': 2020-09-04 06:26:43.459000, 'end': ...
 2226875  [{'start': 2020-09-04 05:26:43.459000, 'end': ...
 ...                                                    ...
 2372918  [{'start': 2021-01-30 22:10:30.470000, 'end': ...
 2369085  [{'start': 2021-01-28 03:34:00, 'end': 2021-01...
 2369084  [{'start': 2021-01-28 03:34:00, 'end': 2021-01...
 2353632  [{'start': 2021-01-11 09:37:49, 'end': 2021-01...
 2353592  [{'start': 2021-01-11 09:28:45, 'end': 2021-01...

                                                    windows       id  \
 2333096  {'2m0a.clma.ogg': Timestamp('2020-12-22 06:52:...  2333096
 2226632  {'2m0a.clma.ogg': Timestamp('2020-09-03 05:27:...  2226632
 2287707  {'2m0a.clma.coj': Timestamp('2020-11-07 12:50:...  2287707
 2226876  {'2m0a.clma.ogg': Timestamp('2020-09-04 06:26:...  2226876
 2226875  {'2m0a.clma.ogg': Timestamp('2020-09-04 05:26:...  2226875
 ...                                                    ...      ...
 2372918  {'2m0a.clma.ogg': Timestamp('2021-01-31 05:04:...  2372918
 2369085  {'2m0a.clma.coj': Timestamp('2021-01-28 12:33:...  2369085
 2369084  {'2m0a.clma.coj': Timestamp('2021-01-28 14:54:...  2369084
 2353632  {'2m0a.clma.ogg': Timestamp('2021-01-12 04:53:...  2353632
 2353592  {'2m0a.clma.ogg': Timestamp('2021-01-11 09:28:...  2353592

          ipp_value                 created      proposal_id optimization_type  \
 2333096        1.0 2020-12-16 12:43:13.185     CON2020B-001              TIME
 2226632        1.0 2020-09-03 15:37:32.988    NOAO2020B-005              TIME
 2287707        1.0 2020-11-07 08:40:11.922  FTPEPO2014A-004              TIME
 2226876        1.0 2020-09-03 22:00:29.823       auto_focus              TIME
 2226875        1.0 2020-09-03 22:00:29.034       auto_focus              TIME
 ...            ...                     ...              ...               ...
 2372918        1.0 2021-01-30 22:10:32.311     DDT2020B-010              TIME
 2369085        1.0 2021-01-28 03:21:12.991     ANU2020B-001              TIME
 2369084        1.0 2021-01-28 03:19:30.333     ANU2020B-001              TIME
 2353632        1.0 2021-01-11 09:48:30.001     TAU2020B-002              TIME
 2353592        1.0 2021-01-11 09:37:11.722     TAU2020B-002              TIME

         total_duration acceptibility_cutoff                valid_telescopes  \
 2333096          21404              21404.0  [2m0a.clma.coj, 2m0a.clma.ogg]
 2226632            838                838.0  [2m0a.clma.coj, 2m0a.clma.ogg]
 2287707           1032               1032.0  [2m0a.clma.coj, 2m0a.clma.ogg]
 2226876            720                720.0                 [2m0a.clma.ogg]
 2226875            720                720.0                 [2m0a.clma.ogg]
 ...                ...                  ...                             ...
 2372918           2445               2444.5  [2m0a.clma.coj, 2m0a.clma.ogg]
 2369085           1908               1907.5  [2m0a.clma.coj, 2m0a.clma.ogg]
 2369084           1908               1907.5  [2m0a.clma.coj, 2m0a.clma.ogg]
 2353632           3866               3866.0  [2m0a.clma.coj, 2m0a.clma.ogg]
 2353592           3866               3866.0  [2m0a.clma.coj, 2m0a.clma.ogg]

                                    target_constraint_pairs  \
 2333096  [{'target': {'id': 5162764, 'name': 'WASP-12',...
 2226632  [{'target': {'id': 4645863, 'name': 'ZTF20abtx...
 2287707  [{'target': {'id': 4945583, 'name': 'FTPBK01',...
 2226876  [{'target': {'id': 4647806, 'name': 'auto_focu...
 2226875  [{'target': {'id': 4647805, 'name': 'auto_focu...
 ...                                                    ...
 2372918  [{'target': {'id': 5379639, 'name': 'sn2021pc'...
 2369085  [{'target': {'id': 5364270, 'name': 'NGC3783',...
 2369084  [{'target': {'id': 5364265, 'name': 'IC4329A',...
 2353632  [{'target': {'id': 5281840, 'name': 'T2', 'typ...
 2353592  [{'target': {'id': 5281796, 'name': 'T1', 'typ...

                          win_start                    win_end
 2333096 2020-12-22 06:52:00.000000 2020-12-22 12:52:00.000000
 2226632 2020-09-03 05:27:41.294630 2020-09-03 08:27:23.885378
 2287707 2020-11-07 12:50:00.000000 2020-11-07 13:12:00.000000
 2226876 2020-09-04 06:26:43.459000 2020-09-04 07:26:43.459000
 2226875 2020-09-04 05:26:43.546826 2020-09-04 06:26:43.459000
 ...                            ...                        ...
 2372918 2021-01-31 05:04:50.762038 2021-01-31 06:44:54.383453
 2369085 2021-01-28 12:33:37.701264 2021-01-31 18:32:16.281317
 2369084 2021-01-28 14:05:07.676015 2021-01-31 18:32:16.281317
 2353632 2021-01-12 04:53:49.053229 2021-01-28 06:11:03.621517
 2353592 2021-01-11 09:28:45.000000 2021-01-31 13:36:57.849602

 [8953 rows x 13 columns],
 'proposals': {'OGG_calib': 1000,
  'MuSCAT Commissioning': 40,
  'CON2020B-009': 30,
  'CON2020B-001': 30,
  'auto_focus': 10,
  'TAU2020B-002': 100,
  'TAU2020B-008': 30,
  'TAU2020B-012': 10,
  'KEY2020B-006': 100,
  'LCOEngineering': 1000,
  'NOAO2020B-015': 10,
  'LCO2020B-003': 100,
  'TAU2020B-004': 100,
  'SUPA2020B-006': 10,
  'LCO2020B-001': 100,
  'NOAO2020B-007': 30,
  'ANU2020B-001': 100,
  'NOAO2020B-011': 10,
  'FTP2020B-003': 10,
  'DDT2020B-010': 10,
  'CON2020B-003': 30,
  'FTPEPO2014A-004': 10,
  'COJ_calib': 1000,
  'CON2020B-005': 30,
  'KEY2020B-007': 10,
  'HAW2020B-001': 100,
  'NOAO2020B-005': 100,
  'NOAO2020B-009': 10,
  'LCO2020B-006': 100,
  'LCOEPO2014B-010': 10,
  'NOAO2020B-012': 10,
  'HAW2020B-002': 10,
  'KEY2020B-003': 100,
  'KEY2020B-002': 100,
  'KEY2020B-005': 100},
 'dataset_id': 'edf06014-9f7f-468e-9527-5d92874c4b9e'}

In [74]:
a = d1["all_requests"].to_dict(orient="index")
a

{2333096: {'original_windows': [{'start': Timestamp('2020-12-22 06:52:00'),
    'end': Timestamp('2020-12-22 12:52:00')}],
  'windows': {'2m0a.clma.ogg': {'timepoints': "[{'time': Timestamp('2020-12-22 06:52:00'), 'type': 'start'}, {'time': Timestamp('2020-12-22 12:52:00'), 'type': 'end'}]", 'label': 'None'}},
  'id': 2333096,
  'ipp_value': 1.0,
  'created': Timestamp('2020-12-16 12:43:13.185000'),
  'proposal_id': 'CON2020B-001',
  'optimization_type': 'TIME',
  'total_duration': 21404,
  'acceptibility_cutoff': 21404.0,
  'valid_telescopes': ['2m0a.clma.coj', '2m0a.clma.ogg'],
  'target_constraint_pairs': [{'target': {'id': 5162764,
     'name': 'WASP-12',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 97.6366528287125,
     'dec': 29.6722962039328,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': -1.58,
     'proper_motion_dec': -6.958,
     'epoch': 2000.0,
     'parallax': 2.3122,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 5164910,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 5164943,
     'max_airmass': 2.0,
     'min_lunar_distance': 30.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 5164910}}],
  'win_start': Timestamp('2020-12-22 06:52:00'),
  'win_end': Timestamp('2020-12-22 12:52:00')},
 2226632: {'original_windows': [{'start': Timestamp('2020-09-03 00:21:00'),
    'end': Timestamp('2020-09-03 20:21:00')}],
  'windows': {'2m0a.clma.ogg': {'timepoints': "[{'time': Timestamp('2020-09-03 05:27:41.294630'), 'type': 'start'}, {'time': Timestamp('2020-09-03 08:27:23.885378'), 'type': 'end'}]", 'label': 'None'}},
  'id': 2226632,
  'ipp_value': 1.0,
  'created': Timestamp('2020-09-03 15:37:32.988000'),
  'proposal_id': 'NOAO2020B-005',
  'optimization_type': 'TIME',
  'total_duration': 838,
  'acceptibility_cutoff': 838.0,
  'valid_telescopes': ['2m0a.clma.coj', '2m0a.clma.ogg'],
  'target_constraint_pairs': [{'target': {'id': 4645863,
     'name': 'ZTF20abtxwfx',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 250.338384,
     'dec': 57.139027,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4648042,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 4648042,
     'max_airmass': 1.9,
     'min_lunar_distance': 5.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 4648042}}],
  'win_start': Timestamp('2020-09-03 05:27:41.294630'),
  'win_end': Timestamp('2020-09-03 08:27:23.885378')},
 2287707: {'original_windows': [{'start': Timestamp('2020-11-07 12:50:00'),
    'end': Timestamp('2020-11-07 13:12:00')}],
  'windows': {'2m0a.clma.coj': {'timepoints': "[{'time': Timestamp('2020-11-07 12:50:00'), 'type': 'start'}, {'time': Timestamp('2020-11-07 13:12:00'), 'type': 'end'}]", 'label': 'None'}},
  'id': 2287707,
  'ipp_value': 1.0,
  'created': Timestamp('2020-11-07 08:40:11.922000'),
  'proposal_id': 'FTPEPO2014A-004',
  'optimization_type': 'TIME',
  'total_duration': 1032,
  'acceptibility_cutoff': 1032.0,
  'valid_telescopes': ['2m0a.clma.coj', '2m0a.clma.ogg'],
  'target_constraint_pairs': [{'target': {'id': 4945583,
     'name': 'FTPBK01',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 359.44945,
     'dec': -13.171225,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4947729,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 4947762,
     'max_airmass': 1.6,
     'min_lunar_distance': 30.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 4947729}}],
  'win_start': Timestamp('2020-11-07 12:50:00'),
  'win_end': Timestamp('2020-11-07 13:12:00')},
 2226876: {'original_windows': [{'start': Timestamp('2020-09-04 06:26:43.459000'),
    'end': Timestamp('2020-09-04 07:26:43.459000')}],
  'windows': {'2m0a.clma.ogg': {'timepoints': "[{'time': Timestamp('2020-09-04 06:26:43.459000'), 'type': 'start'}, {'time': Timestamp('2020-09-04 07:26:43.459000'), 'type': 'end'}]", 'label': 'None'}},
  'id': 2226876,
  'ipp_value': 1.0,
  'created': Timestamp('2020-09-03 22:00:29.823000'),
  'proposal_id': 'auto_focus',
  'optimization_type': 'TIME',
  'total_duration': 720,
  'acceptibility_cutoff': 720.0,
  'valid_telescopes': ['2m0a.clma.ogg'],
  'target_constraint_pairs': [{'target': {'id': 4647806,
     'name': 'auto_focus',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 270.7602496675113,
     'dec': 39.0,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4649985,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 4649985,
     'max_airmass': 2.0,
     'min_lunar_distance': 50.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 4649985}}],
  'win_start': Timestamp('2020-09-04 06:26:43.459000'),
  'win_end': Timestamp('2020-09-04 07:26:43.459000')},
 2226875: {'original_windows': [{'start': Timestamp('2020-09-04 05:26:43.459000'),
    'end': Timestamp('2020-09-04 06:26:43.459000')}],
  'windows': {'2m0a.clma.ogg': {'timepoints': "[{'time': Timestamp('2020-09-04 05:26:43.546826'), 'type': 'start'}, {'time': Timestamp('2020-09-04 06:26:43.459000'), 'type': 'end'}]", 'label': 'None'}},
  'id': 2226875,
  'ipp_value': 1.0,
  'created': Timestamp('2020-09-03 22:00:29.034000'),
  'proposal_id': 'auto_focus',
  'optimization_type': 'TIME',
  'total_duration': 720,
  'acceptibility_cutoff': 720.0,
  'valid_telescopes': ['2m0a.clma.ogg'],
  'target_constraint_pairs': [{'target': {'id': 4647805,
     'name': 'auto_focus',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 284.219182573525,
     'dec': 26.0,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4649984,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 4649984,
     'max_airmass': 2.0,
     'min_lunar_distance': 50.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 4649984}}],
  'win_start': Timestamp('2020-09-04 05:26:43.546826'),
  'win_end': Timestamp('2020-09-04 06:26:43.459000')},
 2287709: {'original_windows': [{'start': Timestamp('2020-11-07 11:47:00'),
    'end': Timestamp('2020-11-07 12:00:00')}],
  'windows': {'2m0a.clma.coj': {'timepoints': "[{'time': Timestamp('2020-11-07 11:47:00'), 'type': 'start'}, {'time': Timestamp('2020-11-07 12:00:00'), 'type': 'end'}]", 'label': 'None'}},
  'id': 2287709,
  'ipp_value': 1.0,
  'created': Timestamp('2020-11-07 08:50:14.541000'),
  'proposal_id': 'FTPEPO2014A-004',
  'optimization_type': 'TIME',
  'total_duration': 754,
  'acceptibility_cutoff': 754.0,
  'valid_telescopes': ['2m0a.clma.coj', '2m0a.clma.ogg'],
  'target_constraint_pairs': [{'target': {'id': 4945585,
     'name': 'FTPBK01',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 359.44945,
     'dec': -13.171225,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4947731,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 4947764,
     'max_airmass': 1.6,
     'min_lunar_distance': 30.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 4947731}}],
  'win_start': Timestamp('2020-11-07 11:47:00'),
  'win_end': Timestamp('2020-11-07 12:00:00')},
 2226631: {'original_windows': [{'start': Timestamp('2020-09-03 15:30:14.549000'),
    'end': Timestamp('2020-09-04 15:30:14.549000')}],
  'windows': {'2m0a.clma.ogg': {'timepoints': "[{'time': Timestamp('2020-09-04 05:26:43.546826'), 'type': 'start'}, {'time': Timestamp('2020-09-04 08:17:34.793327'), 'type': 'end'}]", 'label': 'None'}},
  'id': 2226631,
  'ipp_value': 1.0,
  'created': Timestamp('2020-09-03 15:30:16.345000'),
  'proposal_id': 'KEY2020B-002',
  'optimization_type': 'TIME',
  'total_duration': 4245,
  'acceptibility_cutoff': 4244.5,
  'valid_telescopes': ['2m0a.clma.coj', '2m0a.clma.ogg'],
  'target_constraint_pairs': [{'target': {'id': 4645860,
     'name': 'at2020sjv',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 260.7695375,
     'dec': 55.0724527778,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4648039,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 4648039,
     'max_airmass': 1.6,
     'min_lunar_distance': 20.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 4648039}},
   {'target': {'id': 4645861,
     'name': 'at2020sjv',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 260.7695375,
     'dec': 55.0724527778,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4648040,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 4648040,
     'max_airmass': 1.6,
     'min_lunar_distance': 20.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 4648040}},
   {'target': {'id': 4645862,
     'name': 'at2020sjv',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 260.7695375,
     'dec': 55.0724527778,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4648041,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 4648041,
     'max_airmass': 1.6,
     'min_lunar_distance': 20.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 4648041}}],
  'win_start': Timestamp('2020-09-04 05:26:43.546826'),
  'win_end': Timestamp('2020-09-04 08:17:34.793327')},
 2275161: {'original_windows': [{'start': Timestamp('2020-11-08 13:00:00'),
    'end': Timestamp('2020-11-08 17:00:00')}],
  'windows': {'2m0a.clma.coj': {'timepoints': "[{'time': Timestamp('2020-11-08 13:12:39.695011'), 'type': 'start'}, {'time': Timestamp('2020-11-08 17:00:00'), 'type': 'end'}]", 'label': 'None'},
   '2m0a.clma.ogg': {'timepoints': "[{'time': Timestamp('2020-11-08 13:00:00'), 'type': 'start'}, {'time': Timestamp('2020-11-08 15:41:31.876585'), 'type': 'end'}]", 'label': 'None'}},
  'id': 2275161,
  'ipp_value': 1.0,
  'created': Timestamp('2020-10-24 19:17:44.432000'),
  'proposal_id': 'FTPEPO2014A-004',
  'optimization_type': 'TIME',
  'total_duration': 608,
  'acceptibility_cutoff': 608.0,
  'valid_telescopes': ['2m0a.clma.coj', '2m0a.clma.ogg'],
  'target_constraint_pairs': [{'target': {'id': 4900406,
     'name': 'C/2020 M3',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 80.8916666667,
     'dec': -3.0644444444,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4902552,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 4902585,
     'max_airmass': 1.6,
     'min_lunar_distance': 30.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 4902552}}],
  'win_start': Timestamp('2020-11-08 13:00:00'),
  'win_end': Timestamp('2020-11-08 17:00:00')},
 2226877: {'original_windows': [{'start': Timestamp('2020-09-04 07:26:43.459000'),
    'end': Timestamp('2020-09-04 08:26:43.459000')}],
  'windows': {'2m0a.clma.ogg': {'timepoints': "[{'time': Timestamp('2020-09-04 07:26:43.459000'), 'type': 'start'}, {'time': Timestamp('2020-09-04 08:26:43.459000'), 'type': 'end'}]", 'label': 'None'}},
  'id': 2226877,
  'ipp_value': 1.0,
  'created': Timestamp('2020-09-03 22:00:30.381000'),
  'proposal_id': 'auto_focus',
  'optimization_type': 'TIME',
  'total_duration': 720,
  'acceptibility_cutoff': 720.0,
  'valid_telescopes': ['2m0a.clma.ogg'],
  'target_constraint_pairs': [{'target': {'id': 4647807,
     'name': 'auto_focus',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 285.80131676145373,
     'dec': 33.0,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4649986,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},
    'constraints': {'id': 4649986,
     'max_airmass': 2.0,
     'min_lunar_distance': 50.0,
     'max_lunar_phase': 1.0,
     'max_seeing': nan,
     'min_transparency': nan,
     'extra_params': {},
     'configuration_id': 4649986}}],
  'win_start': Timestamp('2020-09-04 07:26:43.459000'),
  'win_end': Timestamp('2020-09-04 08:26:43.459000')},
 2226878: {'original_windows': [{'start': Timestamp('2020-09-04 08:26:43.459000'),
    'end': Timestamp('2020-09-04 09:26:43.459000')}],
  'windows': {'2m0a.clma.ogg': {'timepoints': "[{'time': Timestamp('2020-09-04 08:26:43.459000'), 'type': 'start'}, {'time': Timestamp('2020-09-04 09:26:43.459000'), 'type': 'end'}]", 'label': 'None'}},
  'id': 2226878,
  'ipp_value': 1.0,
  'created': Timestamp('2020-09-03 22:00:30.887000'),
  'proposal_id': 'auto_focus',
  'optimization_type': 'TIME',
  'total_duration': 720,
  'acceptibility_cutoff': 720.0,
  'valid_telescopes': ['2m0a.clma.ogg'],
  'target_constraint_pairs': [{'target': {'id': 4647808,
     'name': 'auto_focus',
     'type': 'ICRS',
     'hour_angle': nan,
     'ra': 306.8423838582765,
     'dec': 29.0,
     'altitude': None,
     'azimuth': None,
     'proper_motion_ra': 0.0,
     'proper_motion_dec': 0.0,
     'epoch': 2000.0,
     'parallax': 0.0,
     'scheme': '',
     'epochofel': nan,
     'orbinc': nan,
     'longascnode': nan,
     'longofperih': None,
     'argofperih': nan,
     'meandist': nan,
     'perihdist': nan,
     'eccentricity': nan,
     'meanlong': None,
     'meananom': nan,
     'dailymot': nan,
     'epochofperih': nan,
     'extra_params': '{}',
     'configuration_id': 4649987,
     'diff_altitude_acceleration': None,
     'diff_altitude_rate': None,
     'diff_azimuth_acceleration': None,
     'diff_azimuth_rate': None,
     'diff_epoch': None},

In [14]:
counts = {}
for prop_id, val in d1["proposals"].items():
    if val not in counts:
        counts[val] = 0
    counts[val] += 1
counts

{1000: 3, 40: 1, 30: 6, 10: 13, 100: 12}

## VWT

In [58]:
for item in os.walk("input_files/vwt"):
    for filename in item[2]:
        filepath = os.path.join(item[0], filename)
        d2 = pickle.load(open(filepath, "rb"))["all_requests"]
        print(filename, len(d2), len(d2[d2["windows"].apply(bool)]))

# filepath = "input_files/vwt/vwt_2020-08.pkl"
# d2 = pickle.load(open(filepath, "rb"))
# d2

vwt_2020-08.pkl 8953 8952
vwt_2021-02.pkl 15941 15940
vwt_2021-08.pkl 11642 11642
vwt_2022-02.pkl 11624 11621

In [62]:
len(d2)

11624

In [63]:
d3 = d2[~d2["windows"].apply(bool)]
d3

,original_windows,old_windows,id,ipp_value,created,proposal_id,optimization_type,total_duration,acceptibility_cutoff,valid_telescopes,target_constraint_pairs,win_start,win_end,new_window_length,new_availability_windows,windows
2906361,"[{'start': 2022-05-27 00:00:00, 'end': 2022-06...",{'2m0a.clma.coj': Timestamp('2022-05-28 08:06:...,2906361,1.05,2022-05-26 10:03:49.890,FTPEPO2014A-004,TIME,528,528.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 7901069, 'name': '67P', 'ty...",2022-05-28 08:06:08.260204,2022-05-30 08:15:00,3.0,"[{'start': 2022-05-28 08:06:08.260204, 'end': ...",{}
2907343,"[{'start': 2022-05-28 00:04:00, 'end': 2022-05...",{'2m0a.clma.coj': Timestamp('2022-05-28 08:06:...,2907343,1.05,2022-05-27 15:07:15.243,FTPEPO2014A-004,TIME,528,528.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 7907947, 'name': '67P', 'ty...",2022-05-28 08:06:08.260204,2022-05-28 08:19:00,1.0,"[{'start': 2022-05-28 08:06:08.260204, 'end': ...",{}
2911000,"[{'start': 2022-05-31 01:46:00, 'end': 2022-06...",{'2m0a.clma.ogg': Timestamp('2022-05-31 05:54:...,2911000,1.0,2022-05-31 20:13:03.206,HAW2022A-002,TIME,2862,2862.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 7930815, 'name': 'C2020 J1'...",2022-05-31 05:54:56.408360,2022-06-01 06:46:00,1.0,"[{'start': 2022-05-31 05:54:56.408360, 'end': ...",{}

In [67]:
print("Original Availability Windows:")
print(d3.iloc[0]["original_windows"])
print("Old Windows:")
print(d3.iloc[0]["old_windows"])
print("New Availability Windows:")
print(d3.iloc[0]["new_availability_windows"])
print("Total Duration:")
print(d3.iloc[0]["total_duration"])

Original Availability Windows:
[{'start': Timestamp('2022-05-27 00:00:00'), 'end': Timestamp('2022-06-03 00:00:00')}]
Old Windows:
{'2m0a.clma.coj': {'timepoints': "[{'time': Timestamp('2022-05-28 08:06:08.260204'), 'type': 'start'}, {'time': Timestamp('2022-05-28 08:15:00'), 'type': 'end'}, {'time': Timestamp('2022-05-29 08:05:53.464343'), 'type': 'start'}, {'time': Timestamp('2022-05-29 08:15:00'), 'type': 'end'}, {'time': Timestamp('2022-05-30 08:05:39.992943'), 'type': 'start'}, {'time': Timestamp('2022-05-30 08:15:00'), 'type': 'end'}]", 'label': 'None'}}
New Availability Windows:
[{'start': Timestamp('2022-05-28 08:06:08.260204'), 'end': Timestamp('2022-05-31 08:06:08.260204')}]
Total Duration:
528

In [69]:
528 - (8*60)

48

In [39]:
df = d2["all_requests"]
df

,original_windows,old_windows,id,ipp_value,created,proposal_id,optimization_type,total_duration,acceptibility_cutoff,valid_telescopes,target_constraint_pairs,win_start,win_end,new_window_length,new_availability_windows,windows
2333096,"[{'start': 2020-12-22 06:52:00, 'end': 2020-12...",{'2m0a.clma.ogg': Timestamp('2020-12-22 06:52:...,2333096,1.05,2020-12-16 12:43:13.185,CON2020B-001,TIME,21404,21404.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5162764, 'name': 'WASP-12',...",2020-12-22 06:52:00.000000,2020-12-22 12:52:00.000000,7.0,"[{'start': 2020-12-22 06:52:00, 'end': 2020-12...",{'2m0a.clma.ogg': Timestamp('2020-12-22 06:52:...
2226632,"[{'start': 2020-09-03 00:21:00, 'end': 2020-09...",{'2m0a.clma.ogg': Timestamp('2020-09-03 05:27:...,2226632,1.05,2020-09-03 15:37:32.988,NOAO2020B-005,TIME,838,838.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 4645863, 'name': 'ZTF20abtx...",2020-09-03 05:27:41.294630,2020-09-03 08:27:23.885378,7.0,"[{'start': 2020-09-03 00:21:00, 'end': 2020-09...",{'2m0a.clma.ogg': Timestamp('2020-09-03 05:27:...
2287707,"[{'start': 2020-11-07 12:50:00, 'end': 2020-11...",{'2m0a.clma.coj': Timestamp('2020-11-07 12:50:...,2287707,1.05,2020-11-07 08:40:11.922,FTPEPO2014A-004,TIME,1032,1032.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 4945583, 'name': 'FTPBK01',...",2020-11-07 12:50:00.000000,2020-11-07 13:12:00.000000,3.0,"[{'start': 2020-11-07 12:50:00, 'end': 2020-11...",{'2m0a.clma.coj': Timestamp('2020-11-07 12:50:...
2226876,"[{'start': 2020-09-04 06:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 06:26:...,2226876,1.05,2020-09-03 22:00:29.823,auto_focus,TIME,720,720.0,[2m0a.clma.ogg],"[{'target': {'id': 4647806, 'name': 'auto_focu...",2020-09-04 06:26:43.459000,2020-09-04 07:26:43.459000,1.0,"[{'start': 2020-09-04 06:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 06:26:...
2226875,"[{'start': 2020-09-04 05:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 05:26:...,2226875,1.05,2020-09-03 22:00:29.034,auto_focus,TIME,720,720.0,[2m0a.clma.ogg],"[{'target': {'id': 4647805, 'name': 'auto_focu...",2020-09-04 05:26:43.546826,2020-09-04 06:26:43.459000,1.0,"[{'start': 2020-09-04 05:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 05:26:...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372918,"[{'start': 2021-01-30 22:10:30.470000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2021-01-31 05:04:...,2372918,1.0,2021-01-30 22:10:32.311,DDT2020B-010,TIME,2445,2444.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5379639, 'name': 'sn2021pc'...",2021-01-31 05:04:50.762038,2021-01-31 06:44:54.383453,7.0,"[{'start': 2021-01-30 22:10:30.470000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2021-01-31 05:04:...
2369085,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 12:33:...,2369085,1.05,2021-01-28 03:21:12.991,ANU2020B-001,TIME,1908,1907.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5364270, 'name': 'NGC3783',...",2021-01-28 12:33:37.701264,2021-01-31 18:32:16.281317,3.0,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 12:33:...
2369084,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 14:54:...,2369084,1.05,2021-01-28 03:19:30.333,ANU2020B-001,TIME,1908,1907.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5364265, 'name': 'IC4329A',...",2021-01-28 14:05:07.676015,2021-01-31 18:32:16.281317,7.0,"[{'start': 2021-01-28 03:34:00, 'end': 2021-02...",{'2m0a.clma.coj': Timestamp('2021-01-28 14:54:...
2353632,"[{'start': 2021-01-11 09:37:49, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-12 04:53:...,2353632,1.1,2021-01-11 09:48:30.001,TAU2020B-002,TIME,3866,3866.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5281840, 'name': 'T2', 'typ...",2021-01-12 04:53:49.053229,2021-01-28 06:11:03.621517,7.0,"[{'start': 2021-01-11 09:37:49, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-12 04:53:...
2353592,"[{'start': 2021-01-11 09:28:45, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-11 09:28:...,2353592,1.1,2021-01-11 09:37:11.722,TAU2020B-002,TIME,3866,3866.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5281796, 'name': 'T1', 'typ...",2021-01-11 09:28:45.000000,2021-01-31 13:36:57.849602,7.0,"[{'start': 2021-01-11 09:28:45, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-11 09:28:...

In [42]:
def get_longest_window(windows):
    start = min([w.timepoints[0]["time"] for t, w in windows.items()])
    end = max([w.timepoints[-1]["time"] for t, w in windows.items()])
    return end - start

In [47]:
df["old_windows"].apply(bool).sum()

8953

In [46]:
len(df["windows"])

8953

In [45]:
df["windows"].apply(bool).sum()

8906

In [ ]:
def get_

In [ ]:
df["old_windows"a

In [50]:
df

,original_windows,old_windows,id,ipp_value,created,proposal_id,optimization_type,total_duration,acceptibility_cutoff,valid_telescopes,target_constraint_pairs,win_start,win_end,new_window_length,new_availability_windows,windows
2333096,"[{'start': 2020-12-22 06:52:00, 'end': 2020-12...",{'2m0a.clma.ogg': Timestamp('2020-12-22 06:52:...,2333096,1.05,2020-12-16 12:43:13.185,CON2020B-001,TIME,21404,21404.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5162764, 'name': 'WASP-12',...",2020-12-22 06:52:00.000000,2020-12-22 12:52:00.000000,7.0,"[{'start': 2020-12-22 06:52:00, 'end': 2020-12...",{'2m0a.clma.ogg': Timestamp('2020-12-22 06:52:...
2226632,"[{'start': 2020-09-03 00:21:00, 'end': 2020-09...",{'2m0a.clma.ogg': Timestamp('2020-09-03 05:27:...,2226632,1.05,2020-09-03 15:37:32.988,NOAO2020B-005,TIME,838,838.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 4645863, 'name': 'ZTF20abtx...",2020-09-03 05:27:41.294630,2020-09-03 08:27:23.885378,7.0,"[{'start': 2020-09-03 00:21:00, 'end': 2020-09...",{'2m0a.clma.ogg': Timestamp('2020-09-03 05:27:...
2287707,"[{'start': 2020-11-07 12:50:00, 'end': 2020-11...",{'2m0a.clma.coj': Timestamp('2020-11-07 12:50:...,2287707,1.05,2020-11-07 08:40:11.922,FTPEPO2014A-004,TIME,1032,1032.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 4945583, 'name': 'FTPBK01',...",2020-11-07 12:50:00.000000,2020-11-07 13:12:00.000000,3.0,"[{'start': 2020-11-07 12:50:00, 'end': 2020-11...",{'2m0a.clma.coj': Timestamp('2020-11-07 12:50:...
2226876,"[{'start': 2020-09-04 06:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 06:26:...,2226876,1.05,2020-09-03 22:00:29.823,auto_focus,TIME,720,720.0,[2m0a.clma.ogg],"[{'target': {'id': 4647806, 'name': 'auto_focu...",2020-09-04 06:26:43.459000,2020-09-04 07:26:43.459000,1.0,"[{'start': 2020-09-04 06:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 06:26:...
2226875,"[{'start': 2020-09-04 05:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 05:26:...,2226875,1.05,2020-09-03 22:00:29.034,auto_focus,TIME,720,720.0,[2m0a.clma.ogg],"[{'target': {'id': 4647805, 'name': 'auto_focu...",2020-09-04 05:26:43.546826,2020-09-04 06:26:43.459000,1.0,"[{'start': 2020-09-04 05:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 05:26:...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372918,"[{'start': 2021-01-30 22:10:30.470000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2021-01-31 05:04:...,2372918,1.0,2021-01-30 22:10:32.311,DDT2020B-010,TIME,2445,2444.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5379639, 'name': 'sn2021pc'...",2021-01-31 05:04:50.762038,2021-01-31 06:44:54.383453,7.0,"[{'start': 2021-01-30 22:10:30.470000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2021-01-31 05:04:...
2369085,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 12:33:...,2369085,1.05,2021-01-28 03:21:12.991,ANU2020B-001,TIME,1908,1907.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5364270, 'name': 'NGC3783',...",2021-01-28 12:33:37.701264,2021-01-31 18:32:16.281317,3.0,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 12:33:...
2369084,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 14:54:...,2369084,1.05,2021-01-28 03:19:30.333,ANU2020B-001,TIME,1908,1907.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5364265, 'name': 'IC4329A',...",2021-01-28 14:05:07.676015,2021-01-31 18:32:16.281317,7.0,"[{'start': 2021-01-28 03:34:00, 'end': 2021-02...",{'2m0a.clma.coj': Timestamp('2021-01-28 14:54:...
2353632,"[{'start': 2021-01-11 09:37:49, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-12 04:53:...,2353632,1.1,2021-01-11 09:48:30.001,TAU2020B-002,TIME,3866,3866.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5281840, 'name': 'T2', 'typ...",2021-01-12 04:53:49.053229,2021-01-28 06:11:03.621517,7.0,"[{'start': 2021-01-11 09:37:49, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-12 04:53:...
2353592,"[{'start': 2021-01-11 09:28:45, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-11 09:28:...,2353592,1.1,2021-01-11 09:37:11.722,TAU2020B-002,TIME,3866,3866.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5281796, 'name': 'T1', 'typ...",2021-01-11 09:28:45.000000,2021-01-31 13:36:57.849602,7.0,"[{'start': 2021-01-11 09:28:45, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-11 09:28:...

In [49]:
df[~df["windows"].apply(bool)][["original_windows", "old_windows", "new_availability_windows"]]

,original_windows,old_windows,new_availability_windows
2166132,"[{'start': 2020-09-13 09:57:00, 'end': 2020-09...",{'2m0a.clma.coj': Timestamp('2020-09-17 18:57:...,"[{'start': 2020-09-13 09:57:00, 'end': 2020-09..."
2166047,"[{'start': 2020-10-04 09:26:00, 'end': 2020-10...",{'2m0a.clma.coj': Timestamp('2020-10-09 18:27:...,"[{'start': 2020-10-04 09:26:00, 'end': 2020-10..."
2166159,"[{'start': 2020-09-20 09:59:00, 'end': 2020-09...",{'2m0a.clma.coj': Timestamp('2020-09-25 18:48:...,"[{'start': 2020-09-20 09:59:00, 'end': 2020-09..."
2166363,"[{'start': 2020-12-26 13:33:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2020-12-27 17:48:...,"[{'start': 2020-12-26 13:33:00, 'end': 2020-12..."
2166479,"[{'start': 2021-01-23 22:18:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-27 18:20:...,"[{'start': 2021-01-23 22:18:00, 'end': 2021-01..."
2166499,"[{'start': 2021-01-23 22:37:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-30 18:21:...,"[{'start': 2021-01-23 22:37:00, 'end': 2021-01..."
2166459,"[{'start': 2021-01-23 22:45:00, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-27 16:02:...,"[{'start': 2021-01-23 22:45:00, 'end': 2021-01..."
2166276,"[{'start': 2021-01-09 23:14:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-13 18:04:...,"[{'start': 2021-01-09 23:14:00, 'end': 2021-01..."
2166731,"[{'start': 2020-12-05 12:45:00, 'end': 2020-12...",{'2m0a.clma.ogg': Timestamp('2020-12-06 15:48:...,"[{'start': 2020-12-05 12:45:00, 'end': 2020-12..."
2166758,"[{'start': 2021-01-23 12:48:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 18:17:...,"[{'start': 2021-01-23 12:48:00, 'end': 2021-01..."
2166657,"[{'start': 2021-01-23 12:58:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-25 18:16:...,"[{'start': 2021-01-23 12:58:00, 'end': 2021-01..."
2166832,"[{'start': 2020-12-19 22:20:00, 'end': 2020-12...",{'2m0a.clma.coj': Timestamp('2020-12-26 17:48:...,"[{'start': 2020-12-19 22:20:00, 'end': 2020-12..."
2188926,"[{'start': 2020-07-22 14:20:10, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2020-09-05 19:10:...,"[{'start': 2020-07-22 14:20:10, 'end': 2020-07..."
2188941,"[{'start': 2020-07-22 14:20:10, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2020-09-09 18:54:...,"[{'start': 2020-07-22 14:20:10, 'end': 2020-07..."
2188973,"[{'start': 2020-07-22 14:20:10, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2020-08-02 19:45:...,"[{'start': 2020-07-22 14:20:10, 'end': 2020-07..."
2188974,"[{'start': 2020-07-22 14:20:10, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2020-08-05 19:33:...,"[{'start': 2020-07-22 14:20:10, 'end': 2020-07..."
2198349,"[{'start': 2020-07-31 20:01:14.730000, 'end': ...",{'2m0a.clma.coj': Timestamp('2020-08-02 13:48:...,"[{'start': 2020-07-31 20:01:14.730000, 'end': ..."
2189006,"[{'start': 2020-07-22 14:20:10, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2020-08-04 19:44:...,"[{'start': 2020-07-22 14:20:10, 'end': 2020-07..."
2202995,"[{'start': 2020-08-07 00:00:00, 'end': 2020-08...",{'2m0a.clma.coj': Timestamp('2020-08-08 11:54:...,"[{'start': 2020-08-07 00:00:00, 'end': 2020-08..."
2189007,"[{'start': 2020-07-22 14:20:10, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2020-08-08 19:28:...,"[{'start': 2020-07-22 14:20:10, 'end': 2020-07..."
2220927,"[{'start': 2020-08-26 20:00:51.843000, 'end': ...",{'2m0a.clma.coj': Timestamp('2020-09-02 18:06:...,"[{'start': 2020-08-26 20:00:51.843000, 'end': ..."
2232941,"[{'start': 2020-09-10 20:00:41.811000, 'end': ...",{'2m0a.clma.coj': Timestamp('2020-09-17 17:47:...,"[{'start': 2020-09-10 20:00:41.811000, 'end': ..."
2244929,"[{'start': 2020-09-22 19:13:13, 'end': 2020-10...",{'2m0a.clma.coj': Timestamp('2020-09-26 11:00:...,"[{'start': 2020-09-22 19:13:13, 'end': 2020-09..."
2244933,"[{'start': 2020-09-22 19:13:13, 'end': 2020-10...",{'2m0a.clma.coj': Timestamp('2020-09-26 11:00:...,"[{'start': 2020-09-22 19:13:13, 'end': 2020-09..."
2244931,"[{'start': 2020-09-22 19:13:13, 'end': 2020-10...",{'2m0a.clma.coj': Timestamp('2020-09-26 11:00:...,"[{'start': 2020-09-22 19:13:13, 'end': 2020-09..."
2244930,"[{'start': 2020-09-22 19:13:13, 'end': 2020-10...",{'2m0a.clma.coj': Timestamp('2020-09-26 11:00:...,"[{'start': 2020-09-22 19:13:13, 'end': 2020-09..."
2287141,"[{'start': 2020-11-06 12:00:53, 'end': 2020-11...",{'2m0a.clma.coj': Timestamp('2020-11-09 15:45:...,"[{'start': 2020-11-06 12:00:53, 'end': 2020-11..."
2267489,"[{'start': 2020-10-15 20:41:41, 'end': 2020-10...",{'2m0a.clma.ogg': Timestamp('2020-10-17 15:26:...,"[{'start': 2020-10-15 20:41:41, 'end': 2020-10..."
2339831,"[{'start': 2020-12-24 14:00:00, 'end': 2020-12...",{'2m0a.clma.coj': Timestamp('2020-12-26 10:11:...,"[{'start': 2020-12-24 14:00:00, 'end': 2020-12..."
2214131,"[{'start': 2020-10-28 16:30:00, 'end': 2020-12...",{'2m0a.clma.ogg': Timestamp('2020-11-01 15:19:...,"[{'start': 2020-10-28 16:30:00, 'end': 2020-10..."
2321016,"[{'start': 2020-12-08 23:43:00, 'end': 2020-12...",{'2m0a.clma.coj': Timestamp('2020-12-18 17:26:...,"[{'start': 2020-12-08 23:43:00, 'end': 2020-12..."
2347415,"[{'start': 2021-01-04 15:17:31, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-09 12:32:...,"[{'start': 2021-01-04 15:17:31, 'end': 2021-01..."
2358708,"[{'start': 2021-01-16 00:00:00, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-21 04:59:...,"[{'start': 2021-01-16 00:00:00, 'end': 2021-01..."
2358709,"[{'start': 2021-01-16 00:00:00, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-21 04:59:...,"[{'start': 2021-01-16 00:00:00, 'end': 2021-01..."
2358710,"[{'start': 2021-01-16 00:00:00, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-21 04:59:...,"[{'start': 2021-01-16 00:00:00, 'end': 2021-01..."
2358742,"[{'start': 2021-01-16 00:00:00, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-21 04:59:...,"[{'start': 2021-01-16 00:00:00, 'end': 2021-01..."
2359050,"[{'start': 2021-01-19 05:10:00, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-24 05:00:...,"[{'start': 2021-01-19 05:10:00, 'end': 2021-01..."
2365463,"[{'start': 2021-01-24 23:09:00, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-27 06:54:...,"[{'start': 2021-01-24 23:09:00, 'end': 2021-01..."
2165209,"[{'start': 2020-08-08 15:21:00, 'end': 2020-08...",{'2m0a.clma.ogg': Timestamp('2020-08-13 15:07:...,"[{'start': 2020-08-08 15:21:00, 'end': 2020-08..."
2366226,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-28 05:03:...,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01..."
2366229,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 10:04:...,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01..."
2366231,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-28 05:03:...,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01..."
2366232,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 10:04:...,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01..."
2366234,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 10:04:...,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01..."
2366235,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 10:04:...,"[{'start': 2021-01-25 01:03:00, 'end': 2021-01..."
2166218,"[{'start': 2021-01-02 22:09:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-05 17:54:...,"[{'start': 2021-01-02 22:09:00, 'end': 2021-01..."
2165354,"[{'start': 2021-01-17 00:49:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-18 17:58:...,"[{'start': 2021-01-17 00:49:00, 'end': 2021-01..."

In [43]:
df["windows"].apply(get_longest_window)

ValueError: min() arg is an empty sequence

In [40]:
df["windows"].iloc[0]

{'2m0a.clma.ogg': {'timepoints': "[{'time': Timestamp('2020-12-22 06:52:00'), 'type': 'start'}, {'time': Timestamp('2020-12-22 15:15:43.114500'), 'type': 'end'}, {'time': Timestamp('2020-12-23 06:22:00.793203'), 'type': 'start'}, {'time': Timestamp('2020-12-23 15:11:47.312368'), 'type': 'end'}, {'time': Timestamp('2020-12-24 06:18:05.001056'), 'type': 'start'}, {'time': Timestamp('2020-12-24 15:07:51.510493'), 'type': 'end'}, {'time': Timestamp('2020-12-25 06:14:09.209083'), 'type': 'start'}, {'time': Timestamp('2020-12-25 15:03:55.708943'), 'type': 'end'}, {'time': Timestamp('2020-12-26 06:10:13.417304'), 'type': 'start'}, {'time': Timestamp('2020-12-26 14:59:59.907711'), 'type': 'end'}, {'time': Timestamp('2020-12-27 06:06:17.625642'), 'type': 'start'}, {'time': Timestamp('2020-12-27 14:56:04.106683'), 'type': 'end'}]", 'label': 'None'}}

In [41]:
df

,original_windows,old_windows,id,ipp_value,created,proposal_id,optimization_type,total_duration,acceptibility_cutoff,valid_telescopes,target_constraint_pairs,win_start,win_end,new_window_length,new_availability_windows,windows
2333096,"[{'start': 2020-12-22 06:52:00, 'end': 2020-12...",{'2m0a.clma.ogg': Timestamp('2020-12-22 06:52:...,2333096,1.05,2020-12-16 12:43:13.185,CON2020B-001,TIME,21404,21404.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5162764, 'name': 'WASP-12',...",2020-12-22 06:52:00.000000,2020-12-22 12:52:00.000000,7.0,"[{'start': 2020-12-22 06:52:00, 'end': 2020-12...",{'2m0a.clma.ogg': Timestamp('2020-12-22 06:52:...
2226632,"[{'start': 2020-09-03 00:21:00, 'end': 2020-09...",{'2m0a.clma.ogg': Timestamp('2020-09-03 05:27:...,2226632,1.05,2020-09-03 15:37:32.988,NOAO2020B-005,TIME,838,838.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 4645863, 'name': 'ZTF20abtx...",2020-09-03 05:27:41.294630,2020-09-03 08:27:23.885378,7.0,"[{'start': 2020-09-03 00:21:00, 'end': 2020-09...",{'2m0a.clma.ogg': Timestamp('2020-09-03 05:27:...
2287707,"[{'start': 2020-11-07 12:50:00, 'end': 2020-11...",{'2m0a.clma.coj': Timestamp('2020-11-07 12:50:...,2287707,1.05,2020-11-07 08:40:11.922,FTPEPO2014A-004,TIME,1032,1032.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 4945583, 'name': 'FTPBK01',...",2020-11-07 12:50:00.000000,2020-11-07 13:12:00.000000,3.0,"[{'start': 2020-11-07 12:50:00, 'end': 2020-11...",{'2m0a.clma.coj': Timestamp('2020-11-07 12:50:...
2226876,"[{'start': 2020-09-04 06:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 06:26:...,2226876,1.05,2020-09-03 22:00:29.823,auto_focus,TIME,720,720.0,[2m0a.clma.ogg],"[{'target': {'id': 4647806, 'name': 'auto_focu...",2020-09-04 06:26:43.459000,2020-09-04 07:26:43.459000,1.0,"[{'start': 2020-09-04 06:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 06:26:...
2226875,"[{'start': 2020-09-04 05:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 05:26:...,2226875,1.05,2020-09-03 22:00:29.034,auto_focus,TIME,720,720.0,[2m0a.clma.ogg],"[{'target': {'id': 4647805, 'name': 'auto_focu...",2020-09-04 05:26:43.546826,2020-09-04 06:26:43.459000,1.0,"[{'start': 2020-09-04 05:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 05:26:...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372918,"[{'start': 2021-01-30 22:10:30.470000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2021-01-31 05:04:...,2372918,1.0,2021-01-30 22:10:32.311,DDT2020B-010,TIME,2445,2444.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5379639, 'name': 'sn2021pc'...",2021-01-31 05:04:50.762038,2021-01-31 06:44:54.383453,7.0,"[{'start': 2021-01-30 22:10:30.470000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2021-01-31 05:04:...
2369085,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 12:33:...,2369085,1.05,2021-01-28 03:21:12.991,ANU2020B-001,TIME,1908,1907.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5364270, 'name': 'NGC3783',...",2021-01-28 12:33:37.701264,2021-01-31 18:32:16.281317,3.0,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 12:33:...
2369084,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 14:54:...,2369084,1.05,2021-01-28 03:19:30.333,ANU2020B-001,TIME,1908,1907.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5364265, 'name': 'IC4329A',...",2021-01-28 14:05:07.676015,2021-01-31 18:32:16.281317,7.0,"[{'start': 2021-01-28 03:34:00, 'end': 2021-02...",{'2m0a.clma.coj': Timestamp('2021-01-28 14:54:...
2353632,"[{'start': 2021-01-11 09:37:49, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-12 04:53:...,2353632,1.1,2021-01-11 09:48:30.001,TAU2020B-002,TIME,3866,3866.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5281840, 'name': 'T2', 'typ...",2021-01-12 04:53:49.053229,2021-01-28 06:11:03.621517,7.0,"[{'start': 2021-01-11 09:37:49, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-12 04:53:...
2353592,"[{'start': 2021-01-11 09:28:45, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-11 09:28:...,2353592,1.1,2021-01-11 09:37:11.722,TAU2020B-002,TIME,3866,3866.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5281796, 'name': 'T1', 'typ...",2021-01-11 09:28:45.000000,2021-01-31 13:36:57.849602,7.0,"[{'start': 2021-01-11 09:28:45, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-11 09:28:...

In [37]:
df.rename(columns={"original_windows": "og_windows", "windows": "original_windows"})

,og_windows,old_windows,id,ipp_value,created,proposal_id,optimization_type,total_duration,acceptibility_cutoff,valid_telescopes,target_constraint_pairs,win_start,win_end,new_window_length,new_availability_windows,original_windows
2333096,"[{'start': 2020-12-22 06:52:00, 'end': 2020-12...",{'2m0a.clma.ogg': Timestamp('2020-12-22 06:52:...,2333096,1.05,2020-12-16 12:43:13.185,CON2020B-001,TIME,21404,21404.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5162764, 'name': 'WASP-12',...",2020-12-22 06:52:00.000000,2020-12-22 12:52:00.000000,7.0,"[{'start': 2020-12-22 06:52:00, 'end': 2020-12...",{'2m0a.clma.ogg': Timestamp('2020-12-22 06:52:...
2226632,"[{'start': 2020-09-03 00:21:00, 'end': 2020-09...",{'2m0a.clma.ogg': Timestamp('2020-09-03 05:27:...,2226632,1.05,2020-09-03 15:37:32.988,NOAO2020B-005,TIME,838,838.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 4645863, 'name': 'ZTF20abtx...",2020-09-03 05:27:41.294630,2020-09-03 08:27:23.885378,7.0,"[{'start': 2020-09-03 00:21:00, 'end': 2020-09...",{'2m0a.clma.ogg': Timestamp('2020-09-03 05:27:...
2287707,"[{'start': 2020-11-07 12:50:00, 'end': 2020-11...",{'2m0a.clma.coj': Timestamp('2020-11-07 12:50:...,2287707,1.05,2020-11-07 08:40:11.922,FTPEPO2014A-004,TIME,1032,1032.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 4945583, 'name': 'FTPBK01',...",2020-11-07 12:50:00.000000,2020-11-07 13:12:00.000000,3.0,"[{'start': 2020-11-07 12:50:00, 'end': 2020-11...",{'2m0a.clma.coj': Timestamp('2020-11-07 12:50:...
2226876,"[{'start': 2020-09-04 06:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 06:26:...,2226876,1.05,2020-09-03 22:00:29.823,auto_focus,TIME,720,720.0,[2m0a.clma.ogg],"[{'target': {'id': 4647806, 'name': 'auto_focu...",2020-09-04 06:26:43.459000,2020-09-04 07:26:43.459000,1.0,"[{'start': 2020-09-04 06:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 06:26:...
2226875,"[{'start': 2020-09-04 05:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 05:26:...,2226875,1.05,2020-09-03 22:00:29.034,auto_focus,TIME,720,720.0,[2m0a.clma.ogg],"[{'target': {'id': 4647805, 'name': 'auto_focu...",2020-09-04 05:26:43.546826,2020-09-04 06:26:43.459000,1.0,"[{'start': 2020-09-04 05:26:43.459000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2020-09-04 05:26:...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372918,"[{'start': 2021-01-30 22:10:30.470000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2021-01-31 05:04:...,2372918,1.0,2021-01-30 22:10:32.311,DDT2020B-010,TIME,2445,2444.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5379639, 'name': 'sn2021pc'...",2021-01-31 05:04:50.762038,2021-01-31 06:44:54.383453,7.0,"[{'start': 2021-01-30 22:10:30.470000, 'end': ...",{'2m0a.clma.ogg': Timestamp('2021-01-31 05:04:...
2369085,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 12:33:...,2369085,1.05,2021-01-28 03:21:12.991,ANU2020B-001,TIME,1908,1907.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5364270, 'name': 'NGC3783',...",2021-01-28 12:33:37.701264,2021-01-31 18:32:16.281317,3.0,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 12:33:...
2369084,"[{'start': 2021-01-28 03:34:00, 'end': 2021-01...",{'2m0a.clma.coj': Timestamp('2021-01-28 14:54:...,2369084,1.05,2021-01-28 03:19:30.333,ANU2020B-001,TIME,1908,1907.5,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5364265, 'name': 'IC4329A',...",2021-01-28 14:05:07.676015,2021-01-31 18:32:16.281317,7.0,"[{'start': 2021-01-28 03:34:00, 'end': 2021-02...",{'2m0a.clma.coj': Timestamp('2021-01-28 14:54:...
2353632,"[{'start': 2021-01-11 09:37:49, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-12 04:53:...,2353632,1.1,2021-01-11 09:48:30.001,TAU2020B-002,TIME,3866,3866.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5281840, 'name': 'T2', 'typ...",2021-01-12 04:53:49.053229,2021-01-28 06:11:03.621517,7.0,"[{'start': 2021-01-11 09:37:49, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-12 04:53:...
2353592,"[{'start': 2021-01-11 09:28:45, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-11 09:28:...,2353592,1.1,2021-01-11 09:37:11.722,TAU2020B-002,TIME,3866,3866.0,"[2m0a.clma.coj, 2m0a.clma.ogg]","[{'target': {'id': 5281796, 'name': 'T1', 'typ...",2021-01-11 09:28:45.000000,2021-01-31 13:36:57.849602,7.0,"[{'start': 2021-01-11 09:28:45, 'end': 2021-01...",{'2m0a.clma.ogg': Timestamp('2021-01-11 09:28:...